### ISSUE TITLE
[DOCS] Pseudo states addon 

### ISSUE THREAD

**Issue by ArkadiuszKrzymienski** [infermedica/component-library#112]
We can improve our docs by adding an addon to Storybook (https://storybook.js.org/addons/storybook-addon-pseudo-states/) that makes it easy to switch between CSS pseudo states of an element (:hover, :active, :focus).

**Comment by pspaczek** [comment]
@ArkadiuszKrzymienski can we close this issue? :)

**Comment by ArkadiuszKrzymienski** [comment]
Decorator for rendering variants of component, including rendering pseudo states, has been implemented and is located on this branch [infermedica:docs/new_tests_and_docs](https://github.com/infermedica/component-library/tree/docs/new_tests_and_docs)
