### ISSUE TITLE
[BUG] MutlipleChoiceItem radio label should not be shrunk.

### ISSUE THREAD

**Issue by mateuszkulpa** [infermedica/component-library#132]
When we set long label for choice item, then radio label can be shrunk.

Current result:
<img width="801" alt="Screenshot 2023-04-03 at 10 04 16" src="https://user-images.githubusercontent.com/17556031/229449103-8bdbefe2-aad4-4126-a513-1aaf374fdcd7.png">

Expected result:
<img width="865" alt="Screenshot 2023-04-03 at 10 08 47" src="https://user-images.githubusercontent.com/17556031/229449812-42b0a8e7-a96b-48c6-84bc-e648c19d1dac.png">

Possible solution:
Set `flex-shrink: 0` on `.ui-multiple-choices-item__choices` class.

**Comment by AlanLes** [comment]
LGTM! Awesome! 😍
