### ISSUE TITLE
[REFACTOR] Use CSS Logical Properties to support LTR languages

### ISSUE THREAD

**Issue by pspaczek** [infermedica/component-library#15]
Try to use all logical properties for `padding`, `margin`, `text-align` and `borders`
https://web.dev/learn/css/logical-properties/ Try to use flex and `gap` instead of margin to handle many cases.

Please create mixins to handle logical properties and remember to use CSS Var
If is possible use shorthand like `margin-inline` or `padding-block`

!!! Please create mixins and make changes in few components. Push it to CR and after approve add changes to other components.

**Comment by pspaczek** [comment]
@AlanLes can you assign to one issue at one time? :thank_you:

**Comment by AlanLes** [comment]
Yep, sorry 😉
