### ISSUE TITLE
a11y: fix focus order in HorizontalPaging

### ISSUE THREAD

**Issue by sonya0504** [infermedica/component-library#336]
Please fix focus order in Horizontal Paging according to the newest order:
<img width="702" alt="image" src="https://github.com/infermedica/component-library/assets/37744371/2ed1e72c-f255-4568-8030-40d98b73eb01">

**Comment by pspaczek** [comment]
fixed on v1.1.3 on #332; arrow navigation added (stable) on v1.5.1
