### ISSUE TITLE
[FEAT] Create Question with multi select

### ISSUE THREAD

**Issue by sonya0504** [infermedica/component-library#356]
According to new design (will provide when will ready) add new component: Question with multiselect

**Comment by pspaczek** [comment]
Please add more information to the issue because we don't know the scope of this issue. Please add screens with the designs.

**Comment by sonya0504** [comment]
When the design will ready, I will add all the necessary information

**Comment by pspaczek** [comment]
Please reopen this Issue when the design is ready.

**Comment by pspaczek** [comment]
Please reopen this Issue when the design is ready.
