### ISSUE TITLE
[FEAT] Get rid of `fast-deep-equal` library.

### ISSUE THREAD

**Issue by AlanLes** [infermedica/component-library#392]
## Is your feature request related to a problem? Please describe.
The `[fast-deep-equal library](https://github.com/epoberezkin/fast-deep-equal)` seems to be no longer supported (last commit four years ago), and it causes troubles over and over. 

## Describe the solution you'd like
It is a good idea to get rid of it and find some other/newer/evergreen library instead. Eventually, we could write our own custom `equal` function since that's the only function we use out of it.

Possible solutions:
- https://www.measurethat.net/Benchmarks/Show/19037/0/fast-deep-equal-vs-jsonstringify-equality-comparison-fo#latest_results_block
- https://github.com/planttheidea/fast-equals

## What are the acceptance criteria?
- The `fast-deep-equal` library no longer exists in the dependencies.
- Every component using the `fast-deep-equal` library works as before with the new solution.

**Comment by kubajmarek** [comment]
> and it causes troubles over and over.

What are those? Just so we can try to avoid them when switching.

**Comment by AlanLes** [comment]
@kubajmarek I can't recall them right now, but we've bypassed them in the `shims-vue.d.ts` in our project. But it's a hack. 
And last weekend, I was playing with [another javascript runner](https://bun.sh/), and the `fast-deep-equal` library hit me again with a bunch of errors.
