### ISSUE TITLE
[FIX] Textarea hasAutogrowing feature

### ISSUE THREAD

**Issue by AlanLes** [infermedica/component-library#451]
## Describe the bug
It doesn't work.

## To Reproduce
1. Go to storybook Atoms / Textarea and toggle the `hasAutogrowing` flag to true
2. Type a lot of characters so that the textarea should grow
3. See the textarea bugged

## Expected behavior
As I understand this functionality - it should grow when the text gets longer and requires it to grow in order to be visible.

## Screenshots
<img width="1137" alt="image" src="https://github.com/infermedica/component-library/assets/13744352/67138ae9-9eee-41ec-a56a-11829c1b29f6">

<img width="783" alt="image" src="https://github.com/infermedica/component-library/assets/13744352/6a0dcb0e-2e1e-4839-93bf-ddf7e6d0d518">

**Comment by pspaczek** [comment]
Everything functions correctly. Please utilize actual values for testing. The issue arises from the lack of spaces in this lengthy text.
![Kapture 2024-04-04 at 08 44 08](https://github.com/infermedica/component-library/assets/12138170/d1ae1b8b-a2ba-493d-8adf-ecfaf48b242b)
