### ISSUE TITLE
[FIX] Adding focus to the first invalid input in UiMultipleChoices

### ISSUE THREAD

**Issue by sonya0504** [infermedica/component-library#452]
## Describe the bug
It is necessary to add `nextTick` in the function `focusOnInvalidChoice` to allow adding focus to the first invalid input after changing state to invalid

## To Reproduce
Steps to reproduce the behaviour:
1. In the application go to view with UiMultipleChoices
2. Without picking any answer click the `Next button`
3. You see errors but the focus stays on the `Next button`
4. Click the `Next button` again
5. See error and focus goes to the first invalid input

## Expected behavior
After first click on the `Next button` focus should go to the the first invalid input

## Screenshots

https://github.com/infermedica/component-library/assets/37744371/6ce0952d-4563-414b-b606-dec893295c30

**Comment by pspaczek** [comment]
resolved
